{{- if .Values.redis.useInternal -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.fullname" . }}-redis"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
{{ include "harbor.labels" . | indent 4 }}
    component: redis
{{- end -}}