{{- if .Values.redis.useInternal -}}
{{- if and .Values.redis.usePassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-redis"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: redis
type: Opaque
data:
  {{- if .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
{{- end -}}