{{- if and .Values.Persistence.Enabled (not .Values.Persistence.ExistingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
{{- if .Values.Persistence.Annotations }}
{{ toYaml .Values.Persistence.Annotations | indent 4 }}
{{- end }}
  {{- if .Values.Persistence.StorageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.Persistence.StorageClass | quote }}
  {{- end }}
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.Persistence.AccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.Persistence.Size | quote }}
{{- end }}
