{{- if .Values.chartmuseum.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "harbor.fullname" . }}-chartmuseum"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: chartmuseum
spec:
  replicas: {{ .Values.chartmuseum.replicas }}
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: chartmuseum
  template:
    metadata:
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: chartmuseum
    spec:
      containers:
      - name: chartmuseum
        image: {{ template "chartmuseum.image" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
{{ toYaml .Values.chartmuseum.resources | indent 10 }}
        envFrom:
        - configMapRef:
            name: "{{ template "harbor.fullname" . }}-chartmuseum"
        - secretRef:
            name: "{{ template "harbor.fullname" . }}-chartmuseum"
        env:
          - name: BASIC_AUTH_PASS
            valueFrom:
              secretKeyRef:
                name: {{ template "harbor.core" . }}
                key: secret
        ports:
        - containerPort: 9999
        volumeMounts:
        - name: chartmuseum-data
          mountPath: /chart_storage
      volumes:
      - name: chartmuseum-data
{{ include "chartmuseum.volume" . | indent 8 }}
{{ include "chartmuseum.nodeSelector" . | indent 6 }}
      {{- with .Values.chartmuseum.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.chartmuseum.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
